### ISSUE TITLE
Point pattern analysis, KDE

### ISSUE THREAD

**Issue by jeffreyevans** [mgimond/mgimond.github.io#1]
In your tutorial on Point Pattern Analysis the assertion that "_The spatstat package has a function called density which implements a gaussian kernel function_" is not entirely correct. The results of spatstat::density.ppp is an isotropic or, if specified, anisotropic density estimate and not a traditional Gaussian KDE.  This is an estimate of the intensity function and not the observed point density. This has been verified by the spatstat developer A. Baddeley. 

Unfortunately, this is not entirely clear in the function help so, it is a completely understandable application of the function. Very nice set of tutorials. Because of the lack of a true weighted/unweighted KDE function in R, I wrote a function `sp.kde` in the spatialEco package.

**Comment by mgimond** [comment]
Thanks, Jeffrey,  for catching that error. And thanks for checking with Baddeley that the function is indeed  adopting an isotropic kernel. The errata should be fixed this summer when I revisit these lecture pages.

**Comment by jeffreyevans** [comment]
Manny,
This really is a nice tutorial which covers a wide gambit of spatial analysis. Thank you for taking the time to compile this material as well as keeping it up to date, I will certainly direct folks to it. I may take some time to organizing some of my teaching material this was as well. I currently use R packages to manage labs but, using GitHub pages this way looks like a quite efficient addition.

If you ever have any spatial or statistical functions that you do not want to develop a package for, I would be more than happy to add you as an author and include them in the spatialEco package (https://github.com/jeffreyevans). I am trying to provide a wide range of spatial and ecological modeling utilities in this package and welcome contributions as well as code improvements.

Best,
Jeff
